/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsVoto;
import Clases.ClsEleccion;
import Clases.ClsMensajes;
import Controladores.CtlCandidato;
import Controladores.CtlEleccion;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hueck
 */
public class VistaGestorEleccion extends javax.swing.JFrame {

    JFrame menuPrincipal;
    ClsMensajes mensaje;
    CtlEleccion controladorEleccion;
    CtlCandidato controladorCandidato;
    String idTemp;
    String estadoTemp;
    int fila;
    String idEleccion;
    String idCandidato;
    String nombre;
    String categoria;
    String estado;
    String ganador;
    String fechaInicio;
    String fechaFin;
    String[] arrayFecha;
    Boolean vacio = false;
    LinkedList<ClsEleccion> listaElecciones;
    LinkedList<ClsCandidato> listaCandidatos;
    LinkedList<ClsVoto> listaCandidatoEleccion;

    /**
     * Creates new form VistaEleccion
     */
    public VistaGestorEleccion(JFrame menuPrincipal) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.controladorEleccion = new CtlEleccion();
        this.controladorCandidato = new CtlCandidato();
        this.botonActualizar.setVisible(false);
        obtenerElecciones();
        obtenerCandidatos();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calendar = Calendar.getInstance();
        Date dateObj = calendar.getTime();
        this.campoFechaInicio.setDate(dateObj);
        this.campoFechaFin.setDate(dateObj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        campoFechaInicio = new com.toedter.calendar.JDateChooser();
        campoFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboCandidato = new javax.swing.JComboBox<>();
        botonAsociarCandidato = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaElecciones = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminarAsociacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCandidatosElecciones = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Fec. Inicio");

        jLabel3.setText("Fec. Fin");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel6.setText("Categoria");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidencial", "Municipal" }));

        jLabel8.setText("Estado");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abierta", "Cerrada" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonActualizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel8)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizar)))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Candidato");

        comboCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCandidatoActionPerformed(evt);
            }
        });

        botonAsociarCandidato.setText("Asociar Candidato");
        botonAsociarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsociarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAsociarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAsociarCandidato)
                .addGap(22, 22, 22))
        );

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Gestion Elecciones");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        tablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Elección", "Fecha Inicio", "Fecha Fin", "Estado", "Ganador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaElecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEleccionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaElecciones);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminarAsociacion.setText("Eliiminar Asociacion");
        botonEliminarAsociacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAsociacionActionPerformed(evt);
            }
        });

        jLabel7.setText("Candidatos por Elección");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tablaCandidatosElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "id_eleccion", "id_candidato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCandidatosElecciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                            .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonEliminarAsociacion)
                                .addGap(44, 44, 44)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(botonVolver))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEliminar))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarAsociacion))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        this.repaint();
        this.menuPrincipal.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        if (this.campoNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El valor del nombre de la elección no puede ser vacio");
        } else {
            nombre = this.campoNombre.getText();
            if (this.comboCategoria.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(this, "El valor de la categoria no puede ser vacio");
            } else {
                categoria = this.comboCategoria.getSelectedItem().toString();
                if (this.campoFechaInicio.getDate().equals("") || (this.campoFechaInicio.getDate() == null)) {
                    JOptionPane.showMessageDialog(this, "El valor de la fecha inicial no puede ser vacio1");
                } else {
                    fechaInicio = formato.format(this.campoFechaInicio.getDate());
                }
                if (this.campoFechaFin.getDate().equals("") || (this.campoFechaFin.getDate() == null)) {
                    JOptionPane.showMessageDialog(this, "El valor de la fecha final no puede ser vacio1");
                } else {
                    fechaFin = formato.format(this.campoFechaFin.getDate());
                    if (fechaInicio.compareTo(fechaFin) > 0) {
                        JOptionPane.showMessageDialog(this, "El valor de la fecha final no puede ser menos a la fecha Inicial");
                    } else {
                        fechaFin = formato.format(this.campoFechaFin.getDate());
                        if (this.comboEstado.getSelectedItem().toString().equals("")) {
                            JOptionPane.showMessageDialog(this, "El valor de la categoria no puede ser vacio");
                        } else {

                            estado = this.comboEstado.getSelectedItem().toString();
                            arrayFecha = fechaInicio.split("-", 2);
                            idEleccion = arrayFecha[0] + "-" + categoria + "-" + nombre;
                            ganador = "";
                            ClsEleccion eleccion = new ClsEleccion(idEleccion, nombre, categoria, estado, ganador, fechaInicio, fechaFin);

                            mensaje = this.controladorEleccion.agregarEleccion(eleccion);
                            if (mensaje.getTipo().equals(ClsMensajes.OK)) {
                                obtenerElecciones();
                                mensaje.mostrarMensajeOk();
                                this.limpiarCampos();
                            } else {
                                if (mensaje.getTipo().equals(ClsMensajes.ERROR)) {
                                    mensaje.mostrarMensajeError();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        int columna = 0;
        fila = this.tablaElecciones.getSelectedRow();
        if (fila >= 0) {
            idTemp = this.tablaElecciones.getValueAt(fila, columna).toString();

            ClsEleccion eleccion = this.buscarEleccion(idTemp);

            if (eleccion != null) {
                this.botonActualizar.setVisible(true);
                this.botonActualizar.setEnabled(true);
                this.campoNombre.setEnabled(false);
                this.botonAgregar.setEnabled(false);
                this.comboCategoria.setEnabled(false);
                this.campoNombre.setText(eleccion.getIdEleccion());
                this.comboCategoria.setSelectedItem(eleccion.getCategoria());
                this.comboEstado.setSelectedItem(eleccion.getEstado());
                ZoneId defaultZoneId = ZoneId.systemDefault();
                LocalDate fechaInit = LocalDate.parse(eleccion.getFechaInicio());
                LocalDate fechaEnd = LocalDate.parse(eleccion.getFechaFin());
                Date fechaInicio = Date.from(fechaInit.atStartOfDay(defaultZoneId).toInstant());
                Date fechaFin = Date.from(fechaEnd.atStartOfDay(defaultZoneId).toInstant());
                this.campoFechaInicio.setDate(fechaInicio);
                this.campoFechaFin.setDate(fechaFin);
            }
        } else {
            mensaje = new ClsMensajes(ClsMensajes.ERROR, "Para Actualizar no puede estar vacia la tabla o debe seleccionar al menos un registro");
            mensaje.mostrarMensajeError();
            this.botonActualizar.setVisible(false);
            this.botonAgregar.setEnabled(true);
            this.campoNombre.setEnabled(true);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int columna = 0;
        fila = this.tablaElecciones.getSelectedRow();
        if (fila >= 0) {
            idTemp = this.tablaElecciones.getValueAt(fila, columna).toString();
            mensaje = this.controladorEleccion.eliminarEleccion(idTemp);
            if (mensaje.getTipo().equals(ClsMensajes.OK)) {
                obtenerElecciones();
                mensaje.mostrarMensajeOk();
            } else {
                if (mensaje.getTipo().equals(ClsMensajes.ERROR)) {
                    mensaje.mostrarMensajeError();
                }
            }
        } else {
            mensaje = new ClsMensajes(ClsMensajes.ERROR, "La Elección a eliminar no puede ser vacio o debe seleccionar por lo menos una fila");
            mensaje.mostrarMensajeError();
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void comboCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCandidatoActionPerformed

    private void botonAsociarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsociarCandidatoActionPerformed
        int columna = 0;
        int columnaEstado = 3;
        fila = this.tablaElecciones.getSelectedRow();
        if (fila >= 0) {
            idTemp = this.tablaElecciones.getValueAt(fila, columna).toString();
            estadoTemp = this.tablaElecciones.getValueAt(fila, columnaEstado).toString();

            if (estadoTemp.equals("Abierta")) {
                ClsEleccion eleccion = this.buscarEleccion(idTemp);

                if (eleccion != null) {
                    this.idEleccion = eleccion.getIdEleccion();
                    String[] partesCombo = this.comboCandidato.getSelectedItem().toString().split("-");
                    this.idCandidato = partesCombo[1];

                    mensaje = this.controladorEleccion.asociarCandidatoEleccion(idEleccion, idCandidato);
                    if (mensaje.getTipo().equals(ClsMensajes.OK)) {
                        obtenerElecciones();
                        mensaje.mostrarMensajeOk();
                        obtenerCandidatosElecciones(idEleccion);
                    } else {
                        if (mensaje.getTipo().equals(ClsMensajes.ERROR)) {
                            mensaje.mostrarMensajeError();
                            obtenerCandidatosElecciones(idEleccion);
                        }
                    }
                }
            } else {
                mensaje = new ClsMensajes(ClsMensajes.ERROR, "No puedes Asociar Candidatos a una Elección Cerrada");
                mensaje.mostrarMensajeError();
            }
        } else {
            mensaje = new ClsMensajes(ClsMensajes.ERROR, "Para Asociar un candidato a una elección, no puede estar vacia la tabla o debe seleccionar al menos un registro del combo de candidatos");
            mensaje.mostrarMensajeError();
        }
    }//GEN-LAST:event_botonAsociarCandidatoActionPerformed

    private void botonEliminarAsociacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAsociacionActionPerformed
        int columnaC = 1;
        int columnaE = 0;
        fila = this.tablaCandidatosElecciones.getSelectedRow();

        if (fila >= 0) {
            idCandidato = this.tablaCandidatosElecciones.getValueAt(fila, columnaE).toString();
            idEleccion = this.tablaCandidatosElecciones.getValueAt(fila, columnaC).toString();

            mensaje = this.controladorEleccion.eliminarCandidatoEleccion(idCandidato, idEleccion);

            if (mensaje.getTipo().equals(ClsMensajes.OK)) {
                obtenerCandidatosElecciones(idEleccion);
                mensaje.mostrarMensajeOk();
            } else {
                if (mensaje.getTipo().equals(ClsMensajes.ERROR)) {
                    mensaje.mostrarMensajeError();
                }
            }
        } else {
            mensaje = new ClsMensajes(ClsMensajes.ERROR, "La Asociacion a eliminar no puede ser vacio o debe seleccionar por lo menos una fila");
            mensaje.mostrarMensajeError();
        }
    }//GEN-LAST:event_botonEliminarAsociacionActionPerformed

    private void tablaEleccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEleccionesMouseClicked
        int columna = 0;
        fila = this.tablaElecciones.getSelectedRow();
        idTemp = this.tablaElecciones.getValueAt(fila, columna).toString();
        this.obtenerCandidatosElecciones(idTemp);
    }//GEN-LAST:event_tablaEleccionesMouseClicked

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed

        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        if (this.campoNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El valor de la descripción de la elección no puede ser vacio");
        } else {
            nombre = this.campoNombre.getText();
            if (this.comboCategoria.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(this, "El valor de la categoria no puede ser vacio");
            } else {
                categoria = this.comboCategoria.getSelectedItem().toString();
                if (this.campoFechaInicio.getDate().equals("") || (this.campoFechaInicio.getDate() == null)) {
                    JOptionPane.showMessageDialog(this, "El valor de la fecha inicial no puede ser vacio");
                } else {
                    fechaInicio = formato.format(this.campoFechaInicio.getDate());
                }
                if (this.campoFechaFin.getDate().equals("") || (this.campoFechaFin.getDate() == null)) {
                    JOptionPane.showMessageDialog(this, "El valor de la fecha final no puede ser vacio");
                } else {
                    fechaFin = formato.format(this.campoFechaFin.getDate());
                    if (fechaInicio.compareTo(fechaFin) > 0) {
                        JOptionPane.showMessageDialog(this, "El valor de la fecha final no puede ser menos a la fecha Inicial");
                    } else {
                        fechaFin = formato.format(this.campoFechaFin.getDate());
                        if (this.comboEstado.getSelectedItem().toString().equals("")) {
                            JOptionPane.showMessageDialog(this, "El valor de la categoria no puede ser vacio");
                        } else {
                            estado = this.comboEstado.getSelectedItem().toString();
                            arrayFecha = fechaInicio.split("-", 2);
                            idEleccion = nombre;
                            ganador = "";
                            ClsEleccion eleccion = new ClsEleccion(idEleccion, nombre, categoria, estado, ganador, fechaInicio, fechaFin);

                            mensaje = this.controladorEleccion.actualizarEleccion(eleccion);
                            if (mensaje.getTipo().equals(ClsMensajes.OK)) {
                                obtenerElecciones();
                                mensaje.mostrarMensajeOk();
                                this.limpiarCampos();
                            } else {
                                if (mensaje.getTipo().equals(ClsMensajes.ERROR)) {
                                    mensaje.mostrarMensajeError();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    public void limpiarCampos() {
        this.campoNombre.setText("");
        this.campoNombre.setEnabled(true);
        this.botonActualizar.setEnabled(false);
        this.botonAgregar.setEnabled(true);
        this.comboEstado.setSelectedIndex(0);
        this.comboCategoria.setSelectedIndex(0);
        this.comboCategoria.setEnabled(true);
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calendar = Calendar.getInstance();
        Date dateObj = calendar.getTime();
        this.campoFechaInicio.setDate(dateObj);
        this.campoFechaFin.setDate(dateObj);

    }

    public void obtenerElecciones() {
        this.listaElecciones = this.controladorEleccion.ObtenerElecciones();
        this.actualizarTabla(listaElecciones);
    }

    public void obtenerCandidatos() {
        this.listaCandidatos = this.controladorCandidato.ObtenerCandidatos();
        this.llenarComboCandidatos(listaCandidatos);
    }

    public void obtenerCandidatosElecciones(String idEleccion) {
        this.listaCandidatoEleccion = this.controladorEleccion.ObtenerCandidatosElecciones(idEleccion);
        this.actualizarTablaCandidatosEleccion(listaCandidatoEleccion);
    }

    public void actualizarTabla(LinkedList<ClsEleccion> elecciones) {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaElecciones.getModel();
        modelo.setRowCount(0);

        for (ClsEleccion c : elecciones) {
            Object[] fila = {c.getIdEleccion(), c.getFechaInicio(), c.getFechaFin(), c.getEstado(), c.getGanador()};
            modelo.addRow(fila);
        }
    }

    public void actualizarTablaCandidatosEleccion(LinkedList<ClsVoto> candidatoEleccion) {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCandidatosElecciones.getModel();
        modelo.setRowCount(0);

        for (ClsVoto c : candidatoEleccion) {
            Object[] fila = {c.getIdEleccion(), c.getIdCandidato()};
            modelo.addRow(fila);
        }
    }

    public void llenarComboCandidatos(LinkedList<ClsCandidato> candidato) {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.comboCandidato.getModel();
        modelo.removeAllElements();
        for (ClsCandidato c : candidato) {
            comboCandidato.addItem(c.getNombre() + "-" + c.getNumeroDocumento());
        }
    }

    public ClsEleccion buscarEleccion(String idEleccion) {
        for (ClsEleccion c : this.listaElecciones) {
            if (idEleccion.equals(c.getIdEleccion())) {
                return c;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGestorEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGestorEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGestorEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGestorEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGestorEleccion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAsociarCandidato;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEliminarAsociacion;
    private javax.swing.JButton botonVolver;
    private com.toedter.calendar.JDateChooser campoFechaFin;
    private com.toedter.calendar.JDateChooser campoFechaInicio;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> comboCandidato;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaCandidatosElecciones;
    private javax.swing.JTable tablaElecciones;
    // End of variables declaration//GEN-END:variables
}
